In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [4]:
# Get Dimension
a.ndim

1

In [5]:
# Get Shape
b.shape

(2, 3)

In [6]:
# Get Type
a.dtype

dtype('int32')

In [7]:
# Get Size
a.itemsize

4

In [8]:
# Get total size
a.nbytes

12

In [9]:
# Get number of elements
a.size

3

In [10]:
#another way to get total size
a.size * a.itemsize


12

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
# Get a specific element [r, c]
a[1, 5]

13

In [13]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [15]:
# Getting a little more fancy [startindex:endindex:stepsize] end index is exclusive, ie enter 1 extra
a[0, 1:6:2]

array([2, 4, 6])

In [16]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [17]:
# changing values of elements
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [18]:
#3-D array
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
# Get specific element (work outside in)
b[0,1,1]

4

In [20]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [22]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [23]:
# Any other number (full_like- dimensions of any other array, a in this example)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [26]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.7511667 , 0.90727644],
       [0.80297325, 0.03111552],
       [0.34884862, 0.61424195],
       [0.96651956, 0.37573176]])

In [27]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 1,  0, -4],
       [ 2,  5, -3],
       [-3,  2, -3]])

In [28]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [30]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z 
# can use -1 instead of 4
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays !!!


In [31]:
# WRONG METHOD AS NO COPY OF a is created nad the changes in be are reflected in a.
a = np.array([1,2,3])
b = a
b[0] = 100

print(a)

[100   2   3]


In [32]:
# RIGHT METHOD
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


### MATHEMATICS


In [33]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [34]:
a + 2

array([3, 4, 5, 6])

In [35]:
a - 2

array([-1,  0,  1,  2])

In [36]:
a * 2

array([2, 4, 6, 8])

In [37]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [38]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [39]:
# Take the sine
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Linear Algebra


In [40]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [41]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [42]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
np.min(stats)

1

In [44]:
np.max(stats)

6

In [47]:
np.max(stats,axis=1)

array([3, 6])

In [45]:
np.sum(stats)

21

In [48]:
np.sum(stats, axis= 0)

array([5, 7, 9])

In [49]:
np.sum(stats, axis= 1)

array([ 6, 15])

### Reorganizing Arrays

In [50]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [51]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [52]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

#### Load Data from File

In [57]:
filedata = np.genfromtxt("N:\YY\data.txt", delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [62]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [61]:
filedata[filedata > 50] 

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [63]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [60]:
# you can index with a list in an array
a = np.array([1,2,3,4,5,6,7,8,9])

a[[1,2,8]]

array([2, 3, 9])